### ISSUE TITLE
How to go full screen?

### ISSUE THREAD

**Issue by vis223** [SenshiSentou/sd-webui-state-manager#4]
You mention it's possible to view in full screen but I can't work out how. I'm using the beta version in Forge.
This is brilliant by the way. Finally someone is fixing this issue. I have wasted hundreds of hours just redoing all my settings tediously time and again after updating or  crashing. It's driven me mad. So thank you

**Comment by Antivash** [comment]
Not sure if it's what you are talking about, but if you click the icon ([Screenshot here](https://i.imgur.com/JplCM2e.png)) next to the close button, it will [expand it to fill](https://i.imgur.com/z4b0qyc.png) the screen. Though it probably won't look like mine exactly, as I have some custom CSS applied to it.

**Comment by SenshiSentou** [comment]
Glad to hear you're finding it useful. Antivash is correct. In case you were using a dark theme and it wasn't showing up, I just pushed a fix
