### ISSUE TITLE
colour coding

### ISSUE THREAD

**Issue by vis223** [SenshiSentou/sd-webui-state-manager#5]
Would it be possible for the coloured dots to change from red/orange to green when settings are loaded correctly? I find myself clicking every button continuously unsure which components  have loaded. The changing colours would give the necessary feedback. Thank you for this terrific extension.

**Comment by SenshiSentou** [comment]
Absolutely, I will try and add this in over the weekend,. Thanks for the suggestion and helping test it!

**Comment by vis223** [comment]
Thank you for your response
If you liked that one I'm sure I've got a few other suggestions in me :-)

**Comment by SenshiSentou** [comment]
This one is in now :) Feel free to drop any others you may have!
