### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by ZeusLT** [SenshiSentou/sd-webui-state-manager#6]
I am using Taithrah/Minimal theme for gradio:
![image](https://github.com/SenshiSentou/sd-webui-state-manager/assets/22300013/10f24ca0-dd9a-41e5-aff6-d9a6cb85f4cb)

Minimized window looks fine:
![image](https://github.com/SenshiSentou/sd-webui-state-manager/assets/22300013/d6000fe6-ce45-4908-80cf-e39bdd07e2ea)
Correction: Fields are still white and text is white as well:
![image](https://github.com/SenshiSentou/sd-webui-state-manager/assets/22300013/c44f02e7-091f-4ad1-b0d8-a8a81dbe2ee6)

But on full screen it looks like this. Text is white on a white field, white background, buttons are not visible:
![image](https://github.com/SenshiSentou/sd-webui-state-manager/assets/22300013/96be040d-a90e-45af-b63b-e7cdba683420)

**Comment by Antivash** [comment]
> I am using Taithrah/Minimal theme for gradio: ![image](https://private-user-images.githubusercontent.com/22300013/313379272-10f24ca0-dd9a-41e5-aff6-d9a6cb85f4cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDEyNzIsIm5iZiI6MTcxMDYwMDk3MiwicGF0aCI6Ii8yMjMwMDAxMy8zMTMzNzkyNzItMTBmMjRjYTAtZGQ5YS00MWU1LWFmZjYtZDlhNmNiODVmNGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE0NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZjQwMTk1N2E3YjdhOWFhNTI4YzM4MWZmNzAwZmU2Y2Q5NWVjNzQ5Y2U1YTU0ZThhNTA5YzBhNDMwMzY0ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5J0I-TQzoTsV9pQNQq00MHxlvpSTlImkU_ixR9Gf_Gw)
> 
> Minimized window looks fine: ![image](https://private-user-images.githubusercontent.com/22300013/313379187-d6000fe6-ce45-4908-80cf-e39bdd07e2ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDEyNzIsIm5iZiI6MTcxMDYwMDk3MiwicGF0aCI6Ii8yMjMwMDAxMy8zMTMzNzkxODctZDYwMDBmZTYtY2U0NS00OTA4LTgwY2YtZTM5YmRkMDdlMmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE0NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNjllZjU4NDEyZDlhZWQ1MDI2OTVlNGM4YzFlMjVhMTFhNjFkOTVmN2VmNmIzMzQ0NDg5NmM3MGY0MTJiNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wBh0NL3ZTSVwiKdhR0G-9BizH3FO5jt1plKvYD2Jj6k) Correction: Fields are still white and text is white as well: ![image](https://private-user-images.githubusercontent.com/22300013/313379423-c44f02e7-091f-4ad1-b0d8-a8a81dbe2ee6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDEyNzIsIm5iZiI6MTcxMDYwMDk3MiwicGF0aCI6Ii8yMjMwMDAxMy8zMTMzNzk0MjMtYzQ0ZjAyZTctMDkxZi00YWQxLWIwZDgtYThhODFkYmUyZWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE0NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MjkwZWUwYzQ5YjlkZDM0M2RlMmViNGQ4ZmU2YWRiNDdmYzQ2ZWRhZDA4YzE1NjIwNWUyMWZmZjE5YjFiN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XX57v6uIfGsBz24aJyV3rZc8ZkxvSOpZkA_ksicGdeg)
> 
> But on full screen it looks like this. Text is white on a white field, white background, buttons are not visible: ![image](https://private-user-images.githubusercontent.com/22300013/313379239-96be040d-a90e-45af-b63b-e7cdba683420.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDEyNzIsIm5iZiI6MTcxMDYwMDk3MiwicGF0aCI6Ii8yMjMwMDAxMy8zMTMzNzkyMzktOTZiZTA0MGQtYTkwZS00NWFmLWI2M2ItZTdjZGJhNjgzNDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE0NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ODMxOTRiNDdmMTZkOGFmMDU5NDUzMDAyNDBkMjA5OWRiNDNkYmZkYjNlNDRkY2Y4Y2Q0NTgxNGM1NTg2ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WaxXGF_B7obDVIRSLSmswrFOBSZs4acpXndTlTjQHX0)


The full panel's background color is on line 134 of the style.css

You can either edit it manually
![image](https://github.com/SenshiSentou/sd-webui-state-manager/assets/336178/d0d2efcb-2001-409d-b3bc-b3ccd3811420)
![image](https://github.com/SenshiSentou/sd-webui-state-manager/assets/336178/6d4b471b-fa62-4592-98b7-b3c08556906e)

or, as is probably the better option, add the following to your user.css in your a1111/forge/sdnext main folder, replacing #00f with whatever color:

```
.sd-webui-sm-modal-panel .sd-webui-sm-side-panel {
  background-color: #00f !important;
}
```

![image](https://github.com/SenshiSentou/sd-webui-state-manager/assets/336178/33987308-7dde-4b2a-9a35-6c457d3c3fd0)
![image](https://github.com/SenshiSentou/sd-webui-state-manager/assets/336178/96b12403-0b86-4e2a-a71a-b4801be9bd11)
![image](https://github.com/SenshiSentou/sd-webui-state-manager/assets/336178/112e1bd3-6b0c-4b23-bdac-9559f130193d)

**Comment by ZeusLT** [comment]
I've pulled v2 and it seems to work properly, I only had to edit `.sd-webui-sm-pill-toggle label` and override white background for some of the fields, the rest seems fine, thanks.
